apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "ufinity-deployment-record-lbl"
  labels:
    app: "ufinity-deployment-record-lbl"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: "ufinity-deployment-record-lbl"
        version: v1
    spec:
      containers:
      - image: mytest.kiwi-internal.com/ufinity_ms_records/dev:201911071604
        imagePullPolicy: Always
        name: "ufinity-deployment-record-lbl"
        env:
          - name: DATABASE_HOST
            value: "ufinity-test.cagh7pb9onik.ap-northeast-1.rds.amazonaws.com"
          - name: DATABASE_NAME
            value: "dev_record_service_db"
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_USER
            value: "dbmaster"
          - name: DATABASE_PASSWORD
            value: "123456789"
        ports:
        - containerPort: 8082
#      imagePullSecrets:
#        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: "ufinity-deployment-record-lbl"
  labels:
    app: "ufinity-deployment-record-lbl"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8082
  selector:
    app: "ufinity-deployment-record-lbl"
