apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "ufinity-deployment-user-lbl"
  labels:
    app: "ufinity-deployment-user-lbl"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: "ufinity-deployment-user-lbl"
        version: v1
    spec:
      containers:
      - image: mytest.kiwi-internal.com/ufinity_ms_enterprise/dev:201911081305
        imagePullPolicy: Always
        name: "ufinity-deployment-user-lbl"
        env:
        - name: DATABASE_HOST
          value: "ufinity-test.cagh7pb9onik.ap-northeast-1.rds.amazonaws.com"
        - name: DATABASE_NAME
          value: "dev_enterprise_service_db"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          value: "dbmaster"
        - name: DATABASE_PASSWORD
          value: "123456789"
        ports:
        - containerPort: 8083
#      imagePullSecrets:
#        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: "ufinity-deployment-user-lbl"
  labels:
    app: "ufinity-deployment-user-lbl"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8083
  selector:
    app: "ufinity-deployment-user-lbl"
